/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.dbConnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ramesh
 */
public class Bills extends javax.swing.JFrame {

    /**
     * Creates new form Bills
     */
    public Bills() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        btn_products = new javax.swing.JButton();
        btn_customers = new javax.swing.JButton();
        btn_bills = new javax.swing.JButton();
        btn_inventry = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_billData = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        radio_billNo = new javax.swing.JRadioButton();
        radio_billDate = new javax.swing.JRadioButton();
        btn_search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(32, 32, 72));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        btn_home.setBackground(new java.awt.Color(102, 102, 102));
        btn_home.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/home_26px.png"))); // NOI18N
        btn_home.setText("Home");
        btn_home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_home.setIconTextGap(15);
        btn_home.setMargin(new java.awt.Insets(2, 25, 2, 14));
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        btn_products.setBackground(new java.awt.Color(102, 102, 102));
        btn_products.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_products.setForeground(new java.awt.Color(255, 255, 255));
        btn_products.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/open_box_26px.png"))); // NOI18N
        btn_products.setText("Products");
        btn_products.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_products.setIconTextGap(15);
        btn_products.setMargin(new java.awt.Insets(2, 25, 2, 14));
        btn_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_productsActionPerformed(evt);
            }
        });

        btn_customers.setBackground(new java.awt.Color(102, 102, 102));
        btn_customers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_customers.setForeground(new java.awt.Color(255, 255, 255));
        btn_customers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/user_24px.png"))); // NOI18N
        btn_customers.setText("Customers");
        btn_customers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_customers.setIconTextGap(15);
        btn_customers.setMargin(new java.awt.Insets(2, 25, 2, 14));
        btn_customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customersActionPerformed(evt);
            }
        });

        btn_bills.setBackground(new java.awt.Color(255, 153, 0));
        btn_bills.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_bills.setForeground(new java.awt.Color(255, 255, 255));
        btn_bills.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/bill_24px.png"))); // NOI18N
        btn_bills.setText("Bills");
        btn_bills.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_bills.setIconTextGap(15);
        btn_bills.setMargin(new java.awt.Insets(2, 25, 2, 14));
        btn_bills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_billsActionPerformed(evt);
            }
        });

        btn_inventry.setBackground(new java.awt.Color(102, 102, 102));
        btn_inventry.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_inventry.setForeground(new java.awt.Color(255, 255, 255));
        btn_inventry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/list_24px.png"))); // NOI18N
        btn_inventry.setText("Inventry");
        btn_inventry.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_inventry.setIconTextGap(15);
        btn_inventry.setMargin(new java.awt.Insets(2, 25, 2, 14));
        btn_inventry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inventryActionPerformed(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(191, 38, 38));
        btn_logout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Logout_26px.png"))); // NOI18N
        btn_logout.setText("Log Out");
        btn_logout.setIconTextGap(15);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_products, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(btn_customers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_bills, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_inventry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_products, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_customers, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_bills, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_inventry, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        tbl_billData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BillNo", "totalPrice", "billDate   [YYYY-MM-DD]", "billTime"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_billData);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        buttonGroup1.add(radio_billNo);
        radio_billNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radio_billNo.setForeground(new java.awt.Color(255, 255, 255));
        radio_billNo.setText("BillNumber");

        buttonGroup1.add(radio_billDate);
        radio_billDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radio_billDate.setForeground(new java.awt.Color(255, 255, 255));
        radio_billDate.setText("BillDate");

        btn_search.setBackground(new java.awt.Color(51, 255, 255));
        btn_search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 992, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio_billNo)
                            .addComponent(radio_billDate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radio_billNo)
                        .addGap(18, 18, 18)
                        .addComponent(radio_billDate))
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        //System.exit(0);
        dispose();
        VLogin log = new VLogin();
        log.setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        dispose();
        Dashboard homeWindow = new Dashboard();
        homeWindow.setVisible(true);
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_productsActionPerformed
        // TODO add your handling code here:
        dispose();
        Products productWindow = new Products();
        productWindow.setVisible(true);
    }//GEN-LAST:event_btn_productsActionPerformed

    private void btn_customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customersActionPerformed
        // TODO add your handling code here:
        dispose();
        VCustomers customerWindow = new VCustomers();
        customerWindow.setVisible(true);
    }//GEN-LAST:event_btn_customersActionPerformed

    private void btn_billsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_billsActionPerformed
        // TODO add your handling code here:
        dispose();
        Bills billWindow = new Bills();
        billWindow.setVisible(true);
    }//GEN-LAST:event_btn_billsActionPerformed

    private void btn_inventryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inventryActionPerformed
        // TODO add your handling code here:
        dispose();
        Inventry inventryWindow = new Inventry();
        inventryWindow.setVisible(true);
    }//GEN-LAST:event_btn_inventryActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
     
    }//GEN-LAST:event_btn_searchActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
            dbConnection con = new dbConnection();
            con.createConnection();
            String query = "select * from bill";
            PreparedStatement pst = con.con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            while (rs.next()){
                String billNo = rs.getString("BillNo");
                String total = rs.getString("totalPrice");
                String bDate = rs.getString("billDate");
                String bTime = rs.getString("billTime");

                String tbData[] = {billNo,total,bDate,bTime};

                DefaultTableModel tblModel = (DefaultTableModel)tbl_billData.getModel();
                tblModel.addRow(tbData);
            }
        }catch(Exception e){
        
        }
    }//GEN-LAST:event_formWindowOpened
                                                                                                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bills;
    private javax.swing.JButton btn_customers;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_inventry;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_products;
    private javax.swing.JButton btn_search;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton radio_billDate;
    private javax.swing.JRadioButton radio_billNo;
    private javax.swing.JTable tbl_billData;
    // End of variables declaration//GEN-END:variables
}
