/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.dbConnection;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ramesh
 */
public class Products extends javax.swing.JFrame {

    /**
     * Creates new form Products
     */
    public Products() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        btn_products = new javax.swing.JButton();
        btn_customers = new javax.swing.JButton();
        btn_bills = new javax.swing.JButton();
        btn_inventry = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_product = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_ProductNameValidation = new javax.swing.JLabel();
        txt_prodName = new javax.swing.JTextField();
        txt_inventry = new javax.swing.JTextField();
        lbl_inventryValidation = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        lbl_priceValidation = new javax.swing.JLabel();
        lbl_descriptionValidation = new javax.swing.JLabel();
        txt_description = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btn_addProduct = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_IDorNAME = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        lbl_searchNotFoundinView = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_productName = new javax.swing.JLabel();
        lbl_productID = new javax.swing.JLabel();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        lbl_stocks = new javax.swing.JLabel();
        lbl_price = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl_description = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(32, 32, 72));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        btn_home.setBackground(new java.awt.Color(102, 102, 102));
        btn_home.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/home_26px.png"))); // NOI18N
        btn_home.setText("Home");
        btn_home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_home.setIconTextGap(15);
        btn_home.setMargin(new java.awt.Insets(2, 25, 2, 14));
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        btn_products.setBackground(new java.awt.Color(255, 153, 0));
        btn_products.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_products.setForeground(new java.awt.Color(255, 255, 255));
        btn_products.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/open_box_26px.png"))); // NOI18N
        btn_products.setText("Products");
        btn_products.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_products.setIconTextGap(15);
        btn_products.setMargin(new java.awt.Insets(2, 25, 2, 14));
        btn_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_productsActionPerformed(evt);
            }
        });

        btn_customers.setBackground(new java.awt.Color(102, 102, 102));
        btn_customers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_customers.setForeground(new java.awt.Color(255, 255, 255));
        btn_customers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/user_24px.png"))); // NOI18N
        btn_customers.setText("Customers");
        btn_customers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_customers.setIconTextGap(15);
        btn_customers.setMargin(new java.awt.Insets(2, 25, 2, 14));
        btn_customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customersActionPerformed(evt);
            }
        });

        btn_bills.setBackground(new java.awt.Color(102, 102, 102));
        btn_bills.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_bills.setForeground(new java.awt.Color(255, 255, 255));
        btn_bills.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/bill_24px.png"))); // NOI18N
        btn_bills.setText("Bills");
        btn_bills.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_bills.setIconTextGap(15);
        btn_bills.setMargin(new java.awt.Insets(2, 25, 2, 14));
        btn_bills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_billsActionPerformed(evt);
            }
        });

        btn_inventry.setBackground(new java.awt.Color(102, 102, 102));
        btn_inventry.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_inventry.setForeground(new java.awt.Color(255, 255, 255));
        btn_inventry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/list_24px.png"))); // NOI18N
        btn_inventry.setText("Inventry");
        btn_inventry.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_inventry.setIconTextGap(15);
        btn_inventry.setMargin(new java.awt.Insets(2, 25, 2, 14));
        btn_inventry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inventryActionPerformed(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(191, 38, 38));
        btn_logout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Logout_26px.png"))); // NOI18N
        btn_logout.setText("Log Out");
        btn_logout.setIconTextGap(15);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_products, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(btn_customers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_bills, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_inventry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_products, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_customers, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_bills, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_inventry, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 286, Short.MAX_VALUE)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 153, 0));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(14, 25, 45));

        tbl_product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Price", "Description"
            }
        ));
        jScrollPane1.setViewportView(tbl_product);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("All Products", jPanel3);

        jPanel4.setBackground(new java.awt.Color(14, 25, 45));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Add New Product");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Product Name");

        lbl_ProductNameValidation.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbl_ProductNameValidation.setForeground(new java.awt.Color(255, 0, 0));
        lbl_ProductNameValidation.setText("Product Name can't be Empty!");

        txt_prodName.setBackground(new java.awt.Color(102, 102, 102));
        txt_prodName.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        txt_prodName.setForeground(new java.awt.Color(255, 255, 255));

        txt_inventry.setBackground(new java.awt.Color(102, 102, 102));
        txt_inventry.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        txt_inventry.setForeground(new java.awt.Color(255, 255, 255));

        lbl_inventryValidation.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbl_inventryValidation.setForeground(new java.awt.Color(255, 0, 0));
        lbl_inventryValidation.setText("N/A");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Inventry :");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Price :");

        txt_price.setBackground(new java.awt.Color(102, 102, 102));
        txt_price.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        txt_price.setForeground(new java.awt.Color(255, 255, 255));
        txt_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_priceActionPerformed(evt);
            }
        });

        lbl_priceValidation.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbl_priceValidation.setForeground(new java.awt.Color(255, 0, 0));
        lbl_priceValidation.setText("N/A");

        lbl_descriptionValidation.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbl_descriptionValidation.setForeground(new java.awt.Color(255, 0, 0));
        lbl_descriptionValidation.setText("N/A");

        txt_description.setBackground(new java.awt.Color(102, 102, 102));
        txt_description.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        txt_description.setForeground(new java.awt.Color(255, 255, 255));
        txt_description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descriptionActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Description:");

        btn_addProduct.setBackground(new java.awt.Color(0, 102, 0));
        btn_addProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_addProduct.setForeground(new java.awt.Color(255, 255, 255));
        btn_addProduct.setText("Add Product to Database");
        btn_addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addProductActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(204, 0, 0));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear Form");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_descriptionValidation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txt_description, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 439, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(lbl_inventryValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_inventry, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(lbl_ProductNameValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_prodName, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel1))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_priceValidation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_price, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btn_addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbl_ProductNameValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_prodName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_inventryValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_inventry, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_priceValidation)
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(lbl_descriptionValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_description, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addProduct)
                    .addComponent(btnClear))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add New Product", jPanel4);

        jPanel5.setBackground(new java.awt.Color(14, 25, 45));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("View Product Info.");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Search from Product Name or Product ID");

        txt_IDorNAME.setBackground(new java.awt.Color(102, 102, 102));
        txt_IDorNAME.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        txt_IDorNAME.setForeground(new java.awt.Color(255, 255, 255));

        btn_search.setBackground(new java.awt.Color(0, 102, 0));
        btn_search.setForeground(new java.awt.Color(255, 255, 255));
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        lbl_searchNotFoundinView.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbl_searchNotFoundinView.setForeground(new java.awt.Color(255, 0, 0));
        lbl_searchNotFoundinView.setText("Invalid Product Name / ID or Product Not Exist");

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\EADCW2\\img\\product_80px.png")); // NOI18N

        lbl_productName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_productName.setForeground(new java.awt.Color(255, 255, 255));
        lbl_productName.setText("Product Name");

        lbl_productID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_productID.setForeground(new java.awt.Color(255, 255, 255));
        lbl_productID.setText("Product ID");

        btn_edit.setBackground(new java.awt.Color(0, 51, 153));
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setIcon(new javax.swing.ImageIcon("E:\\EADCW2\\img\\edit_profile_16px.png")); // NOI18N
        btn_edit.setText("Edit");

        btn_delete.setBackground(new java.awt.Color(204, 0, 0));
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setIcon(new javax.swing.ImageIcon("E:\\EADCW2\\img\\Delete_16px.png")); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Price");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Stocks");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Status");

        lbl_status.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_status.setForeground(new java.awt.Color(255, 255, 255));
        lbl_status.setText("N/A");

        lbl_stocks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_stocks.setForeground(new java.awt.Color(255, 255, 255));
        lbl_stocks.setText("N/A");

        lbl_price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_price.setForeground(new java.awt.Color(255, 255, 255));
        lbl_price.setText("N/A");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Description");

        lbl_description.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_description.setForeground(new java.awt.Color(255, 255, 255));
        lbl_description.setText("N/A");
        lbl_description.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_stocks, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_status, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_price, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_description, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btn_edit)
                                .addGap(18, 18, 18)
                                .addComponent(btn_delete))
                            .addComponent(lbl_productName, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_productID, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel6)
                    .addGap(361, 361, 361)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_searchNotFoundinView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_IDorNAME, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                        .addComponent(btn_search, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                    .addGap(25, 25, 25)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(lbl_productName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_productID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit)
                    .addComponent(btn_delete))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_price, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_stocks, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_status, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbl_description, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addGap(43, 43, 43))))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(txt_IDorNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6))
                    .addGap(6, 6, 6)
                    .addComponent(btn_search)
                    .addGap(4, 4, 4)
                    .addComponent(lbl_searchNotFoundinView, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(407, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("View Product", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        //System.exit(0);
        dispose();
        VLogin log = new VLogin();
        log.setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        dispose();
        Dashboard homeWindow = new Dashboard();
        homeWindow.setVisible(true);
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customersActionPerformed
        // TODO add your handling code here:
        dispose();
        VCustomers customerWindow = new VCustomers();
        customerWindow.setVisible(true);
    }//GEN-LAST:event_btn_customersActionPerformed

    private void btn_billsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_billsActionPerformed
        // TODO add your handling code here:
        dispose();
        Bills billWindow = new Bills();
        billWindow.setVisible(true);
    }//GEN-LAST:event_btn_billsActionPerformed

    private void btn_inventryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inventryActionPerformed
        // TODO add your handling code here:
        dispose();
        Inventry inventryWindow = new Inventry();
        inventryWindow.setVisible(true);
    }//GEN-LAST:event_btn_inventryActionPerformed

    private void btn_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_productsActionPerformed
        // TODO add your handling code here:
        dispose();
        Products productWindow = new Products();
        productWindow.setVisible(true);
    }//GEN-LAST:event_btn_productsActionPerformed

    private void txt_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_priceActionPerformed

    private void txt_descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descriptionActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lbl_ProductNameValidation.setVisible(false);
        lbl_descriptionValidation.setVisible(false);
        lbl_inventryValidation.setVisible(false);
        lbl_priceValidation.setVisible(false);
        lbl_searchNotFoundinView.setVisible(false);

        try{
            dbConnection con = new dbConnection();
            con.createConnection();
            String query = "select * from product";
            PreparedStatement pst = con.con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            while (rs.next()){
                String PID = rs.getString("pID");
                String Name = rs.getString("ProductName");
                String price = rs.getString("price");
                String description = rs.getString("Description");

                String tbData[] = {PID,Name,price,description};

                DefaultTableModel tblModel = (DefaultTableModel)tbl_product.getModel();
                tblModel.addRow(tbData);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        lbl_ProductNameValidation.setVisible(false);
        lbl_descriptionValidation.setVisible(false);
        lbl_inventryValidation.setVisible(false);
        lbl_priceValidation.setVisible(false);

        txt_description.setText("");
        txt_inventry.setText("");
        txt_price.setText("");
        txt_prodName.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btn_addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addProductActionPerformed
        // TODO add your handling code here:
        int count = 0;

        if(txt_description.getText().trim().isEmpty()){
            lbl_descriptionValidation.setText("Description can't be Empty!");
            lbl_descriptionValidation.setVisible(true);
        }else{
            count++;
        }

        if(txt_inventry.getText().trim().isEmpty()){
            lbl_inventryValidation.setText("Inventry cant be Empty!");
            lbl_inventryValidation.setVisible(true);
        }else{
            count++;
        }

        if(txt_price.getText().trim().isEmpty()){
            lbl_priceValidation.setText("Price can't be Empty!");
            lbl_priceValidation.setVisible(true);
        }else{
            int price = Integer.parseInt(txt_price.getText());
            if (price < 0){
                lbl_priceValidation.setText("Price can't be less than Zero!");
                lbl_priceValidation.setVisible(true);
            }else{
                count++;
            }
        }

        if(txt_prodName.getText().trim().isEmpty()){
            lbl_ProductNameValidation.setText("Product Name can't be Empty!");
            lbl_ProductNameValidation.setVisible(true);
        }else{
            count++;
        }

        if(count == 4){
            Model.Product prod = new Model.Product();
            prod.insertProduct(txt_prodName.getText(), txt_price.getText(), txt_description.getText(), txt_inventry.getText());
            Boolean st = prod.returnQueryStatus();
            if (st == true){
                VDone done = new VDone();
                done.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null,"Operaion Faild, Error with Databse Connection");
            }            
        }else{
            
        } 
    }//GEN-LAST:event_btn_addProductActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        String nameOrID = txt_IDorNAME.getText();
        Model.Product prod  = new Model.Product();
        prod.searchProduct(nameOrID);
        Boolean qs = prod.returnQueryStatus();
        if(qs == true){
            lbl_productName.setText(prod.Name);
            lbl_productID.setText(prod.PID);
            lbl_price.setText(prod.price);
            lbl_description.setText(prod.description);
            prod.searchStocks();
            lbl_status.setText(prod.stockStatus);
            lbl_stocks.setText(prod.stocoCount);
            lbl_searchNotFoundinView.setVisible(false);
        }else{
            lbl_searchNotFoundinView.setVisible(true);
            lbl_productName.setText("N/A");
            lbl_productID.setText("N/A");
            lbl_price.setText("N/A");
            lbl_stocks.setText("N/A");
            lbl_status.setText("N/A");
            lbl_description.setText("N/A");
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        Model.Product prod = new Model.Product();
        prod.deleteProduct(lbl_productID.getText());
        Boolean st = prod.returnQueryStatus();
        if(st == true){
            VDone done = new VDone();
            done.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Operaion Faild, Error with Databse Connection");
        }
    }//GEN-LAST:event_btn_deleteActionPerformed
                                                                                                                           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btn_addProduct;
    private javax.swing.JButton btn_bills;
    private javax.swing.JButton btn_customers;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_inventry;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_products;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_ProductNameValidation;
    private javax.swing.JLabel lbl_description;
    private javax.swing.JLabel lbl_descriptionValidation;
    private javax.swing.JLabel lbl_inventryValidation;
    private javax.swing.JLabel lbl_price;
    private javax.swing.JLabel lbl_priceValidation;
    private javax.swing.JLabel lbl_productID;
    private javax.swing.JLabel lbl_productName;
    private javax.swing.JLabel lbl_searchNotFoundinView;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JLabel lbl_stocks;
    private javax.swing.JTable tbl_product;
    private javax.swing.JTextField txt_IDorNAME;
    private javax.swing.JTextField txt_description;
    private javax.swing.JTextField txt_inventry;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_prodName;
    // End of variables declaration//GEN-END:variables
}
